name: Build SunamoResult

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoResult
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoResult/SunamoResult.csproj

    - name: Build
      run: dotnet build SunamoResult/SunamoResult.csproj --configuration Release --no-restore

  test:
    name: Test SunamoResult.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoResult.Tests/SunamoResult.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoResult.Tests/SunamoResult.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoResult.Tests/SunamoResult.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
